/**
 * 🪶 CAL Parser Module
 *
 * Semantic Anchoring: Parser transforms CAL source → AST → ActionPlan
 * - Keywords preserve cormorant methodology semantics
 * - Observable properties drive transformations
 * - Immutable results enforce semantic contracts
 *
 * @module parser
 */

import peggy from 'peggy';
import type {
  Program,
  Statement,
  ForageStatement,
  DiveStatement,
  DriftStatement,
  FetchStatement,
  PerchStatement,
  ListenStatement,
  WakeStatement,
  ChirpStatement,
  TraceStatement,
  SurfaceStatement,
  RecallStatement,
  WatchAction,
  ActionPlan,
  ParseResult,
  ParseSuccess,
  ParseError,
  CompileResult,
  DimensionID
} from '../types/index.js';

// ============================================
// PARSER INITIALIZATION
// ============================================

// Load and compile grammar (must be generated by build:grammar script first)
let parser: peggy.Parser;

try {
  // Import the compiled grammar
  const grammarModule = await import('./grammar.js') as any;
  parser = grammarModule.default || grammarModule;
} catch (error) {
  throw new Error(
    'Grammar not compiled. Run "npm run build:grammar" first.\n' +
    'Error: ' + (error as Error).message
  );
}

// ============================================
// PARSE FUNCTION
// ============================================

/**
 * Parse CAL source code into AST
 *
 * Semantic Contract: Preserves keyword meanings from source
 *
 * @param source - CAL source code string
 * @returns ParseResult with success/error
 */
export function parse(source: string): ParseResult {
  try {
    const ast = parser.parse(source) as Program;

    const result: ParseSuccess = {
      success: true,
      ast
    };

    return result;
  } catch (error: any) {
    const parseError: ParseError = {
      success: false,
      error: {
        message: error.message || 'Parse error',
        location: error.location || null,
        expected: error.expected || null,
        found: error.found || null
      }
    };

    return parseError;
  }
}

// ============================================
// AST → ACTION PLAN TRANSFORMATION
// ============================================

/**
 * Transform AST into executable action plan
 *
 * Semantic Anchoring Rules:
 * - FORAGE → query (search behavior)
 * - DIVE → analyze (deep exploration)
 * - DRIFT → drift (gap measurement)
 * - FETCH → fetch (decision logic)
 * - PERCH → observe (position holding)
 * - LISTEN → monitor (signal detection)
 * - WAKE → schedule (time trigger)
 * - CHIRP → alert (vocalization)
 * - TRACE → traceCascade (pathway following)
 * - SURFACE → output (results emergence)
 *
 * @param ast - Abstract Syntax Tree
 * @returns ActionPlan with metadata and actions
 */
export function toActionPlan(ast: Program): ActionPlan {
  const plan: ActionPlan = {
    type: 'ActionPlan',
    generated: new Date().toISOString(),
    methodology: '6D Foraging',
    lens: {
      sound: [],  // ChirpIQX signals
      space: [],  // PerchIQX positions
      time: []    // WakeIQX triggers
    },
    dimensions: [],
    actions: []
  };

  // Transform each statement into actions
  for (const stmt of ast.statements) {
    transformStatement(stmt, plan);
  }

  // Deduplicate dimensions (preserve semantic identity)
  plan.dimensions = [...new Set(plan.dimensions)];

  return Object.freeze(plan) as ActionPlan;
}

/**
 * Transform individual statement into action(s)
 * Semantic Contract: Preserve keyword intent in action type
 */
function transformStatement(stmt: Statement, plan: ActionPlan): void {
  switch (stmt.type) {
    case 'Forage':
      transformForage(stmt, plan);
      break;
    case 'Dive':
      transformDive(stmt, plan);
      break;
    case 'Drift':
      transformDrift(stmt, plan);
      break;
    case 'Fetch':
      transformFetch(stmt, plan);
      break;
    case 'Perch':
      transformPerch(stmt, plan);
      break;
    case 'Listen':
      transformListen(stmt, plan);
      break;
    case 'Wake':
      transformWake(stmt, plan);
      break;
    case 'Chirp':
      transformChirp(stmt, plan);
      break;
    case 'Trace':
      transformTrace(stmt, plan);
      break;
    case 'Watch':
      transformWatch(stmt, plan);
      break;
    case 'Recall':
      transformRecall(stmt as RecallStatement, plan);
      break;
    case 'Surface':
      transformSurface(stmt, plan);
      break;
  }
}

// ============================================
// STATEMENT TRANSFORMERS
// ============================================

function transformForage(stmt: ForageStatement, plan: ActionPlan): void {
  // Transform filter format from grammar (left/right) to data adapter (field/value)
  const transformedFilters = (stmt.where || []).map((filter: any) => ({
    field: filter.left,      // Grammar uses "left" for field name
    operator: filter.operator,
    value: filter.right      // Grammar uses "right" for comparison value
  }));

  plan.actions.push({
    action: 'query',
    target: stmt.target,
    filters: transformedFilters,
    dimensions: stmt.across || [],
    cascadeDepth: stmt.depth || 1,
    output: stmt.surface || 'results'
  });

  // Collect dimensions for analysis
  if (stmt.across) {
    plan.dimensions.push(...stmt.across.map(d => d.id as DimensionID));
  }
}

function transformDive(stmt: DiveStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'analyze',
    target: stmt.target,
    condition: stmt.when || null,
    trace: stmt.trace || 'cascade',
    output: stmt.emit || 'report'
  });
}

function transformDrift(stmt: DriftStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'drift',
    target: stmt.target,
    methodology: stmt.methodology,
    performance: stmt.performance,
    gapType: (stmt.gap || 'auto') as 'curiosity' | 'teaching' | 'auto'
  });
}

function transformFetch(stmt: FetchStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'fetch',
    target: stmt.target,
    threshold: stmt.threshold,
    confidence: stmt.confidence ?? null,
    // TODO: Transform nested statements to actions in Phase 4
    onExecute: stmt.onExecute as any ?? null,
    onConfirm: stmt.onConfirm as any ?? null,
    onQueue: stmt.onQueue as any ?? null,
    onWait: stmt.onWait as any ?? null
  });
}

function transformPerch(stmt: PerchStatement, plan: ActionPlan): void {
  // Add to 3D Lens (Space dimension)
  plan.lens.space.push({
    position: stmt.target,
    observe: stmt.listen || [],
    duration: stmt.wake ?? null,
    alert: stmt.chirp ?? null
  });

  // Add observe action
  plan.actions.push({
    action: 'observe',
    target: stmt.target,
    signals: stmt.listen || [],
    timeout: stmt.wake ?? null,
    onSignal: (stmt.chirp as any) ?? null
  });
}

function transformListen(stmt: ListenStatement, plan: ActionPlan): void {
  // Add to 3D Lens (Sound dimension)
  plan.lens.sound.push({
    signals: stmt.signals
  });

  // Add monitor action
  plan.actions.push({
    action: 'monitor',
    signals: stmt.signals
  });
}

function transformWake(stmt: WakeStatement, plan: ActionPlan): void {
  // Add to 3D Lens (Time dimension)
  plan.lens.time.push({
    trigger: stmt.after,
    then: stmt.action as any
  });

  // Add schedule action
  plan.actions.push({
    action: 'schedule',
    delay: stmt.after,
    then: stmt.action as any
  });
}

function transformChirp(stmt: ChirpStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'alert',
    type: stmt.alert ?? 'info',
    message: stmt.message ?? ''
  });
}

function transformTrace(stmt: TraceStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'traceCascade',
    target: stmt.target,
    from: stmt.from ?? null
  });
}

function transformWatch(stmt: any, plan: ActionPlan): void {
  const watchAction: WatchAction = {
    action: 'watch',
    target: stmt.target,
    condition: stmt.when
  };

  if (stmt.for) {
    watchAction.duration = stmt.for;
  }

  plan.actions.push(watchAction);
}

function transformRecall(stmt: RecallStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'recall',
    target: stmt.target,
    date: stmt.date,
    watches: stmt.watches,
    triggersFired: stmt.triggersFired,
    triggersTotal: stmt.triggersTotal,
    confidenceStated: stmt.confidenceStated,
    confidenceActual: stmt.confidenceActual,
    calibration: stmt.calibration,
    driftAfter: stmt.driftAfter ?? null,
    surfaceOutput: stmt.surfaceOutput ?? null,
    surfaceFormat: stmt.surfaceFormat ?? null,
  });
}

function transformSurface(stmt: SurfaceStatement, plan: ActionPlan): void {
  plan.actions.push({
    action: 'output',
    data: stmt.output ?? 'results',
    format: stmt.format ?? 'json',
    scheduledDate: stmt.scheduledDate ?? null
  });
}

// ============================================
// COMPILE FUNCTION
// ============================================

/**
 * Full pipeline: CAL source → AST → ActionPlan
 *
 * Semantic Contract: Complete transformation chain
 * - Preserves keyword semantics through all stages
 * - Returns immutable results
 *
 * @param source - CAL source code
 * @returns Complete compile result with AST and action plan
 */
export function compile(source: string): CompileResult {
  const parseResult = parse(source);

  if (!parseResult.success) {
    return parseResult as ParseError;
  }

  const actionPlan = toActionPlan(parseResult.ast);

  const result: CompileResult = {
    success: true,
    source,
    ast: parseResult.ast,
    actionPlan
  };

  return Object.freeze(result) as CompileResult;
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

/**
 * Pretty print JSON output
 * @param obj - Object to stringify
 * @returns Formatted JSON string
 */
export function prettyPrint(obj: any): string {
  return JSON.stringify(obj, null, 2);
}

/**
 * Validate that action plan preserves semantic contracts
 * Development mode only
 */
export function validateSemanticContracts(plan: ActionPlan): boolean {
  // Rule 1: All actions must have semantic action types
  const validActions = [
    'query', 'analyze', 'drift', 'fetch', 'observe',
    'monitor', 'schedule', 'alert', 'traceCascade', 'watch', 'recall', 'output'
  ];

  for (const action of plan.actions) {
    if (!validActions.includes(action.action)) {
      throw new Error(`Semantic violation: Invalid action type "${action.action}"`);
    }
  }

  // Rule 2: Dimensions must be semantic IDs (D1-D6, ALL)
  const validDimensions = ['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'ALL'];
  for (const dim of plan.dimensions) {
    if (!validDimensions.includes(dim)) {
      throw new Error(`Semantic violation: Invalid dimension "${dim}"`);
    }
  }

  // Rule 3: 3D Lens must maintain Sound × Space × Time structure
  if (!plan.lens.sound || !plan.lens.space || !plan.lens.time) {
    throw new Error('Semantic violation: 3D Lens structure incomplete');
  }

  return true;
}
